### ISSUE TITLE
Won't make

### ISSUE THREAD

**Issue by geekphazm** [aurovine/AudioCoin#2]
Hello,

I would like to see why your project does not have a "doc" folder with build and installation instructions.

Can you please tell me how to make this and build on a Ubuntu/Unix install?

Thanks!

**Comment by Stoner19** [comment]
geekphazm I just opened a pull request with a doc/ directory that includes compiling instructions.

**Comment by Stoner19** [comment]
This is a very old issue that I'm sure is resolved by now. @locohammerhead please close it.

**Comment by locohammerhead** [comment]
Yeah this is an old issue that was resolved long ago.
